-- 100 official templates (50 free / 50 pro) for the Goal Library.
-- Generated seed - safe to re-run (on conflict do nothing).

insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('19f9ed73-4828-53ec-9671-858ab664db97','2570186a-c329-488a-b106-ddb003647ba7','Couch to 5k','linear',true,false,'Fitness','Zero to your first 5k in gentle stages.','{"goals":[{"key":"g1","title":"Couch to 5k","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Walk 30 minutes, three times this week"},{"key":"n2","parent":null,"title":"Jog 1 min / walk 2 min for 20 minutes"},{"key":"n3","parent":null,"title":"Jog 10 minutes without stopping"},{"key":"n4","parent":null,"title":"Run 2k slow and steady"},{"key":"n5","parent":null,"title":"Run your first full 5k"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('6957418f-0506-5fe8-b64c-b86fe79404bf','2570186a-c329-488a-b106-ddb003647ba7','100 Push-ups Club','linear',true,false,'Fitness','From your first ten to a hundred in one workout.','{"goals":[{"key":"g1","title":"100 Push-ups Club","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"10 push-ups in one set"},{"key":"n2","parent":null,"title":"25 push-ups across a day"},{"key":"n3","parent":null,"title":"40 push-ups in one set"},{"key":"n4","parent":null,"title":"70 push-ups across a workout"},{"key":"n5","parent":null,"title":"100 push-ups in one workout"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('8fdad6e5-7ac9-53f5-8d0d-10bc96d6cacd','2570186a-c329-488a-b106-ddb003647ba7','First Pull-up','linear',true,false,'Fitness','The classic bodyweight milestone, earned step by step.','{"goals":[{"key":"g1","title":"First Pull-up","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Dead hang for 30 seconds"},{"key":"n2","parent":null,"title":"10 slow negative pull-ups"},{"key":"n3","parent":null,"title":"5 band-assisted pull-ups"},{"key":"n4","parent":null,"title":"Chin over the bar with a small jump"},{"key":"n5","parent":null,"title":"One strict full pull-up"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('64c89dff-0084-5b67-b8e8-a27e9005c10d','2570186a-c329-488a-b106-ddb003647ba7','Get in Shape','pyramid',true,false,'Fitness','Movement, food, and sleep — the whole base, built from the bottom.','{"goals":[{"key":"g1","title":"Get in Shape","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Move every day"},{"key":"n2","parent":"n1","title":"Hit 10k steps for a week"},{"key":"n3","parent":"n1","title":"Stretch every morning for two weeks"},{"key":"n4","parent":null,"title":"Eat better"},{"key":"n5","parent":"n4","title":"Cook 4 dinners a week"},{"key":"n6","parent":"n4","title":"Cut sugary drinks for a month"},{"key":"n7","parent":null,"title":"Sleep right"},{"key":"n8","parent":"n7","title":"Same bedtime for a week"},{"key":"n9","parent":"n7","title":"7+ hours a night for a month"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ac193aea-2c68-59d6-8638-75eb5db9fe4b','2570186a-c329-488a-b106-ddb003647ba7','Morning Workout','habit',true,false,'Fitness','Weekday training before the day can interfere.','{"goals":[{"key":"g1","title":"Morning Workout","structure":"habit","days":[1,2,3,4,5],"cue":"I get out of bed","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ebed2df2-3785-5b93-b190-6eb0a2b20d46','2570186a-c329-488a-b106-ddb003647ba7','10k Steps a Day','habit',true,false,'Fitness','The simplest fitness habit that actually works.','{"goals":[{"key":"g1","title":"10k Steps a Day","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I finish lunch","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('fd4cf564-f162-52a6-91cd-9b0900c29171','2570186a-c329-488a-b106-ddb003647ba7','Learn to Swim','tree',true,false,'Fitness','Water confidence first — every skill unlocks the next.','{"goals":[{"key":"g1","title":"Learn to Swim","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Get comfortable in the water"},{"key":"n2","parent":"n1","title":"Float and glide"},{"key":"n3","parent":"n2","title":"Swim 25m freestyle"},{"key":"n4","parent":"n3","title":"Swim 500m without stopping"},{"key":"n5","parent":"n1","title":"Tread water for 2 minutes"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('81b9b2f2-adcb-5ab0-b307-6d446357b645','2570186a-c329-488a-b106-ddb003647ba7','Touch Your Toes','linear',true,false,'Fitness','A flexibility comeback for desk workers.','{"goals":[{"key":"g1","title":"Touch Your Toes","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Daily 5-minute hamstring stretch for a week"},{"key":"n2","parent":null,"title":"Reach mid-shin comfortably"},{"key":"n3","parent":null,"title":"Hold a 60-second forward fold"},{"key":"n4","parent":null,"title":"Palms flat past your toes"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('27e66591-9844-5cfb-966b-a7250fb3b9a8','2570186a-c329-488a-b106-ddb003647ba7','$1,000 Emergency Fund','linear',true,false,'Money','The starter cushion that ends the paycheck panic.','{"goals":[{"key":"g1","title":"$1,000 Emergency Fund","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Open a separate savings account"},{"key":"n2","parent":null,"title":"Save your first $100"},{"key":"n3","parent":null,"title":"Automate a weekly transfer"},{"key":"n4","parent":null,"title":"Reach $500"},{"key":"n5","parent":null,"title":"Reach $1,000"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('77c2e4a4-fe46-5dcb-bb8a-18ac21dffc14','2570186a-c329-488a-b106-ddb003647ba7','Debt Snowball Starter','linear',true,false,'Money','Momentum first: clear the smallest debts and roll the payments.','{"goals":[{"key":"g1","title":"Debt Snowball Starter","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"List every debt smallest to largest"},{"key":"n2","parent":null,"title":"Pay minimums plus $50 on the smallest"},{"key":"n3","parent":null,"title":"Clear your smallest debt"},{"key":"n4","parent":null,"title":"Roll that payment into the next one"},{"key":"n5","parent":null,"title":"Clear your second debt"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('4b7fa61e-9693-5c1d-be36-dab04f3331ee','2570186a-c329-488a-b106-ddb003647ba7','Finances in Order','pyramid',true,false,'Money','Know the numbers, stop the leaks, grow the gap.','{"goals":[{"key":"g1","title":"Finances in Order","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Know your numbers"},{"key":"n2","parent":"n1","title":"Track every expense for 30 days"},{"key":"n3","parent":"n1","title":"Calculate your true monthly burn"},{"key":"n4","parent":null,"title":"Stop the leaks"},{"key":"n5","parent":"n4","title":"Cancel unused subscriptions"},{"key":"n6","parent":"n4","title":"Renegotiate one recurring bill"},{"key":"n7","parent":null,"title":"Grow the gap"},{"key":"n8","parent":"n7","title":"Automate 10% savings"},{"key":"n9","parent":"n7","title":"Set up a high-yield account"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('289a8f8f-4ba8-504e-bba9-0995f0e626e2','2570186a-c329-488a-b106-ddb003647ba7','First Index Fund','linear',true,false,'Money','From zero to invested, without the jargon.','{"goals":[{"key":"g1","title":"First Index Fund","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Open a brokerage account"},{"key":"n2","parent":null,"title":"Understand expense ratios (one article)"},{"key":"n3","parent":null,"title":"Pick a broad index fund"},{"key":"n4","parent":null,"title":"Invest your first $100"},{"key":"n5","parent":null,"title":"Automate a monthly buy"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ae2e75be-4bbb-5290-b290-ec3075bb24b8','2570186a-c329-488a-b106-ddb003647ba7','No-Spend Weekdays','habit',true,false,'Money','Weekdays are for free things; spending waits for Saturday.','{"goals":[{"key":"g1","title":"No-Spend Weekdays","structure":"habit","days":[1,2,3,4,5],"cue":"I get my morning coffee at home","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('76b77eb3-6b64-556e-ba11-a6a630a51d8e','2570186a-c329-488a-b106-ddb003647ba7','Raise Your Credit Score','linear',true,false,'Money','A methodical climb out of the low 600s.','{"goals":[{"key":"g1","title":"Raise Your Credit Score","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pull your free credit report"},{"key":"n2","parent":null,"title":"Dispute any errors"},{"key":"n3","parent":null,"title":"Set every bill to autopay"},{"key":"n4","parent":null,"title":"Get utilization under 30%"},{"key":"n5","parent":null,"title":"Score up 50 points"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('fc1c1626-7713-5af3-9b0f-04d5733277c5','2570186a-c329-488a-b106-ddb003647ba7','Save for a Car','pyramid',true,false,'Money','A car bought with cash — no payment book in the glovebox.','{"goals":[{"key":"g1","title":"Save for a Car","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Set the target"},{"key":"n2","parent":"n1","title":"Pick the model and real price"},{"key":"n3","parent":"n1","title":"Open a dedicated account"},{"key":"n4","parent":null,"title":"Fund it"},{"key":"n5","parent":"n4","title":"Save the first $1,000"},{"key":"n6","parent":"n4","title":"Automate monthly deposits"},{"key":"n7","parent":"n4","title":"Sell something you don''t use"},{"key":"n8","parent":null,"title":"Buy smart"},{"key":"n9","parent":"n8","title":"Get pre-purchase inspection"},{"key":"n10","parent":"n8","title":"Negotiate out the door price"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('0d98235c-6f24-553e-8874-67b3cdaeaa62','2570186a-c329-488a-b106-ddb003647ba7','Land a New Job','linear',true,false,'Career','A focused sprint from resume to offer.','{"goals":[{"key":"g1","title":"Land a New Job","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Rewrite your resume for the target role"},{"key":"n2","parent":null,"title":"List 20 companies you''d actually join"},{"key":"n3","parent":null,"title":"Apply to 10 with tailored notes"},{"key":"n4","parent":null,"title":"Do one mock interview"},{"key":"n5","parent":null,"title":"Negotiate and accept an offer"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('df81f2ba-0585-5e27-8b90-d78c53c8f514','2570186a-c329-488a-b106-ddb003647ba7','Earn a Promotion','pyramid',true,false,'Career','Make the case undeniable before you ask.','{"goals":[{"key":"g1","title":"Earn a Promotion","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Deliver visibly"},{"key":"n2","parent":"n1","title":"Own one high-impact project"},{"key":"n3","parent":"n1","title":"Document your wins monthly"},{"key":"n4","parent":null,"title":"Grow the skills"},{"key":"n5","parent":"n4","title":"Close your biggest skill gap"},{"key":"n6","parent":"n4","title":"Mentor a junior teammate"},{"key":"n7","parent":null,"title":"Make the ask"},{"key":"n8","parent":"n7","title":"Ask your manager what promotion requires"},{"key":"n9","parent":"n7","title":"Present your case in writing"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d3f75023-f361-53be-ba23-5d8011aeca36','2570186a-c329-488a-b106-ddb003647ba7','Portfolio Website','linear',true,false,'Career','A personal site that does your bragging for you.','{"goals":[{"key":"g1","title":"Portfolio Website","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Buy a domain"},{"key":"n2","parent":null,"title":"Pick three projects to showcase"},{"key":"n3","parent":null,"title":"Write a one-paragraph bio"},{"key":"n4","parent":null,"title":"Build and publish the site"},{"key":"n5","parent":null,"title":"Share it in your profiles"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('8415bc2f-09a6-575d-9746-fbccb3457697','2570186a-c329-488a-b106-ddb003647ba7','Ship Something Daily','habit',true,false,'Career','One visible piece of work out the door, every workday.','{"goals":[{"key":"g1","title":"Ship Something Daily","structure":"habit","days":[1,2,3,4,5],"cue":"I sit down at my desk","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('13f86b4f-a4fd-5416-85df-3ae1c52a834d','2570186a-c329-488a-b106-ddb003647ba7','Become a Confident Speaker','tree',true,false,'Career','Each rep on stage unlocks a bigger one.','{"goals":[{"key":"g1","title":"Become a Confident Speaker","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Speak up once in every meeting for a week"},{"key":"n2","parent":"n1","title":"Present to your own team"},{"key":"n3","parent":"n2","title":"Talk at a local meetup"},{"key":"n4","parent":"n3","title":"Speak at a conference"},{"key":"n5","parent":"n1","title":"Record and review yourself once"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('7da9856e-ee0c-5c45-bd19-d1a98f998cf4','2570186a-c329-488a-b106-ddb003647ba7','Start Freelancing','linear',true,false,'Career','First paid gig on the side, without quitting anything.','{"goals":[{"key":"g1","title":"Start Freelancing","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Define one sellable service"},{"key":"n2","parent":null,"title":"Set your rate"},{"key":"n3","parent":null,"title":"Create a one-page offer"},{"key":"n4","parent":null,"title":"Pitch 10 potential clients"},{"key":"n5","parent":null,"title":"Deliver your first paid project"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('b897d2d4-2d9f-5e96-9520-8a722d0f3595','2570186a-c329-488a-b106-ddb003647ba7','Learn to Code','tree',true,false,'Learning','From first course to hireable, unlock by unlock.','{"goals":[{"key":"g1","title":"Learn to Code","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Finish an intro course"},{"key":"n2","parent":"n1","title":"Build a personal website"},{"key":"n3","parent":"n2","title":"Deploy a real project"},{"key":"n4","parent":"n1","title":"Solve 20 practice problems"},{"key":"n5","parent":"n4","title":"Pass a mock technical interview"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ee337495-ecf4-5362-ab60-415bfc4d8ca5','2570186a-c329-488a-b106-ddb003647ba7','Conversational Spanish','linear',true,false,'Learning','Hold a real conversation, not just conjugate verbs.','{"goals":[{"key":"g1","title":"Conversational Spanish","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Learn the 100 most common words"},{"key":"n2","parent":null,"title":"Finish a beginner course"},{"key":"n3","parent":null,"title":"Have a 5-minute exchange with a native speaker"},{"key":"n4","parent":null,"title":"Watch a show with Spanish subtitles"},{"key":"n5","parent":null,"title":"Hold a 30-minute conversation"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('46889f83-c749-503b-b631-9b51f7634565','2570186a-c329-488a-b106-ddb003647ba7','Learn Guitar','tree',true,false,'Learning','Chords unlock songs; songs unlock stages.','{"goals":[{"key":"g1","title":"Learn Guitar","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Learn 4 basic chords"},{"key":"n2","parent":"n1","title":"Play a full song"},{"key":"n3","parent":"n2","title":"Perform for a friend"},{"key":"n4","parent":"n2","title":"Learn barre chords"},{"key":"n5","parent":"n1","title":"Learn fingerpicking"},{"key":"n6","parent":"n5","title":"Fingerpick a full song"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('79d7605a-7c47-5120-b17a-9137f41925c0','2570186a-c329-488a-b106-ddb003647ba7','Read 12 Books This Year','linear',true,false,'Learning','A book a month, tracked like the goal it is.','{"goals":[{"key":"g1","title":"Read 12 Books This Year","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pick your first three books"},{"key":"n2","parent":null,"title":"Finish book 3"},{"key":"n3","parent":null,"title":"Finish book 6"},{"key":"n4","parent":null,"title":"Finish book 9"},{"key":"n5","parent":null,"title":"Finish book 12"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('2a10c0f3-701e-5f94-8a25-00d15c549ee0','2570186a-c329-488a-b106-ddb003647ba7','Daily Reading','habit',true,false,'Learning','Twenty minutes a day beats a yearly resolution.','{"goals":[{"key":"g1","title":"Daily Reading","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I finish dinner","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('43eadab2-4cd3-5007-9d5c-76727a0f9266','2570186a-c329-488a-b106-ddb003647ba7','Chess to 1200','linear',true,false,'Learning','From knowing the moves to a real rating.','{"goals":[{"key":"g1","title":"Chess to 1200","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Learn one opening for white and one for black"},{"key":"n2","parent":null,"title":"Solve 100 tactics puzzles"},{"key":"n3","parent":null,"title":"Play 25 rapid games"},{"key":"n4","parent":null,"title":"Review every loss for a week"},{"key":"n5","parent":null,"title":"Hit 1200 rating"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('2c7eca7e-37fb-56a3-99ae-f3f34c6adbd4','2570186a-c329-488a-b106-ddb003647ba7','Learn to Cook','tree',true,false,'Learning','Knife skills unlock recipes; recipes unlock dinner parties.','{"goals":[{"key":"g1","title":"Learn to Cook","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Master knife basics and 3 techniques"},{"key":"n2","parent":"n1","title":"Cook 5 weeknight staples"},{"key":"n3","parent":"n2","title":"Host a dinner for four"},{"key":"n4","parent":"n1","title":"Bake one thing well"},{"key":"n5","parent":"n4","title":"Bake for an occasion"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('c54df936-05be-54c7-b5e4-1dba94036cc4','2570186a-c329-488a-b106-ddb003647ba7','Touch Typing 80wpm','linear',true,false,'Learning','Stop looking at the keyboard forever.','{"goals":[{"key":"g1","title":"Touch Typing 80wpm","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Learn home row properly"},{"key":"n2","parent":null,"title":"30wpm without looking"},{"key":"n3","parent":null,"title":"50wpm accurately"},{"key":"n4","parent":null,"title":"65wpm daily average"},{"key":"n5","parent":null,"title":"80wpm tested"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('959e6377-eaf9-535f-bed2-f0dced6c7cf4','2570186a-c329-488a-b106-ddb003647ba7','Write a Book','pyramid',true,false,'Creative','Plan, draft, publish — built from the base.','{"goals":[{"key":"g1","title":"Write a Book","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Plan the story"},{"key":"n2","parent":"n1","title":"Outline every chapter"},{"key":"n3","parent":"n1","title":"Develop the main characters"},{"key":"n4","parent":null,"title":"Write the draft"},{"key":"n5","parent":"n4","title":"Write 500 words a day for a month"},{"key":"n6","parent":"n4","title":"Finish the first three chapters"},{"key":"n7","parent":null,"title":"Publish it"},{"key":"n8","parent":"n7","title":"Edit the full manuscript"},{"key":"n9","parent":"n7","title":"Query 10 agents or self-publish"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('7bf585c5-7a8a-5209-9148-d5d174b79ec9','2570186a-c329-488a-b106-ddb003647ba7','Launch a YouTube Channel','linear',true,false,'Creative','From zero to your first ten uploads.','{"goals":[{"key":"g1","title":"Launch a YouTube Channel","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pick a niche you can talk about forever"},{"key":"n2","parent":null,"title":"Record a test video and review it"},{"key":"n3","parent":null,"title":"Publish your first video"},{"key":"n4","parent":null,"title":"Publish 5 videos"},{"key":"n5","parent":null,"title":"Publish 10 and review analytics"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('f3e282fc-65bc-55b8-8b71-987d52e5a239','2570186a-c329-488a-b106-ddb003647ba7','Record a Song','linear',true,false,'Creative','Write it, track it, release it.','{"goals":[{"key":"g1","title":"Record a Song","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Write the lyrics and melody"},{"key":"n2","parent":null,"title":"Make a rough phone demo"},{"key":"n3","parent":null,"title":"Record all the parts properly"},{"key":"n4","parent":null,"title":"Mix and master it"},{"key":"n5","parent":null,"title":"Release it on streaming"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('1a353339-00a9-5eac-a6ce-89070cb9c870','2570186a-c329-488a-b106-ddb003647ba7','Daily Sketching','habit',true,false,'Creative','One page a day; skill compounds quietly.','{"goals":[{"key":"g1","title":"Daily Sketching","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I have my evening tea","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('e66ced0d-7e17-5ca4-b2b0-327bee4bd2eb','2570186a-c329-488a-b106-ddb003647ba7','Start a Blog','linear',true,false,'Creative','Ideas in public, one post at a time.','{"goals":[{"key":"g1","title":"Start a Blog","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Choose the topic and name"},{"key":"n2","parent":null,"title":"Set up the site"},{"key":"n3","parent":null,"title":"Publish your first post"},{"key":"n4","parent":null,"title":"Publish weekly for a month"},{"key":"n5","parent":null,"title":"Reach 10 published posts"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d76f4144-c37b-5e8b-9539-62fa1a555417','2570186a-c329-488a-b106-ddb003647ba7','Photography Portfolio','pyramid',true,false,'Creative','A body of work, not a camera roll.','{"goals":[{"key":"g1","title":"Photography Portfolio","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Build the craft"},{"key":"n2","parent":"n1","title":"Shoot 30 days in a row"},{"key":"n3","parent":"n1","title":"Learn to edit your RAWs"},{"key":"n4","parent":null,"title":"Curate"},{"key":"n5","parent":"n4","title":"Select your best 20 shots"},{"key":"n6","parent":"n4","title":"Get feedback from two photographers"},{"key":"n7","parent":null,"title":"Show it"},{"key":"n8","parent":"n7","title":"Build the portfolio page"},{"key":"n9","parent":"n7","title":"Submit to one exhibit or contest"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('684161da-b295-50c8-96d4-0d72ec66f11a','2570186a-c329-488a-b106-ddb003647ba7','Daily Meditation','habit',true,false,'Mind','Ten quiet minutes that change the other 950.','{"goals":[{"key":"g1","title":"Daily Meditation","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I brush my teeth in the morning","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('cf215709-414d-5a3e-9542-c5d285496aab','2570186a-c329-488a-b106-ddb003647ba7','Nightly Journal','habit',true,false,'Mind','Three lines a night: what happened, what mattered, what''s next.','{"goals":[{"key":"g1","title":"Nightly Journal","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I get into bed","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('e7ac8a8f-f3fb-5607-8da1-3e251053a804','2570186a-c329-488a-b106-ddb003647ba7','Fix Your Sleep','linear',true,false,'Mind','From doomscrolling to eight solid hours.','{"goals":[{"key":"g1","title":"Fix Your Sleep","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pick a fixed wake-up time"},{"key":"n2","parent":null,"title":"No screens 30 minutes before bed for a week"},{"key":"n3","parent":null,"title":"Same bedtime for two weeks"},{"key":"n4","parent":null,"title":"Average 7.5 hours for a month"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('189f4154-12f4-59da-b8bb-3f2e17bbcd18','2570186a-c329-488a-b106-ddb003647ba7','Quit Soda','linear',true,false,'Mind','Taper it down and replace it, not just willpower.','{"goals":[{"key":"g1","title":"Quit Soda","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Count your real weekly cans"},{"key":"n2","parent":null,"title":"Cut to half with sparkling water swaps"},{"key":"n3","parent":null,"title":"One soda a week only"},{"key":"n4","parent":null,"title":"Fully off for 30 days"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d39b57a0-25df-5174-8611-28f6ccf110de','2570186a-c329-488a-b106-ddb003647ba7','Digital Sunset','habit',true,false,'Mind','Phone parked at 10pm; mornings stop starting at midnight.','{"goals":[{"key":"g1","title":"Digital Sunset","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"my 10pm alarm goes off","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('0e37c6aa-5b34-59bb-b1b7-a8169c9d53e0','2570186a-c329-488a-b106-ddb003647ba7','Lose 10 Pounds, Kindly','pyramid',true,false,'Mind','Food, movement, and patience — no crash anything.','{"goals":[{"key":"g1","title":"Lose 10 Pounds, Kindly","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Eat with intention"},{"key":"n2","parent":"n1","title":"Track meals for 14 days"},{"key":"n3","parent":"n1","title":"Protein at every breakfast"},{"key":"n4","parent":null,"title":"Move more"},{"key":"n5","parent":"n4","title":"8k steps daily for two weeks"},{"key":"n6","parent":"n4","title":"Two strength sessions a week"},{"key":"n7","parent":null,"title":"Measure calmly"},{"key":"n8","parent":"n7","title":"Weekly weigh-in only"},{"key":"n9","parent":"n7","title":"Down 10 with a month held steady"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('dd85422c-b3e2-5bd1-9f75-226fb48b94ab','2570186a-c329-488a-b106-ddb003647ba7','Declutter the House','pyramid',true,false,'Home','Room by room until everything has a place.','{"goals":[{"key":"g1","title":"Declutter the House","structure":"pyramid","nodes":[{"key":"n1","parent":null,"title":"Clear the visible"},{"key":"n2","parent":"n1","title":"Declutter every flat surface"},{"key":"n3","parent":"n1","title":"One donation carload out"},{"key":"n4","parent":null,"title":"Tame the hidden"},{"key":"n5","parent":"n4","title":"Closets and drawers"},{"key":"n6","parent":"n4","title":"The garage or storage"},{"key":"n7","parent":null,"title":"Keep it that way"},{"key":"n8","parent":"n7","title":"A home for every item"},{"key":"n9","parent":"n7","title":"10-minute nightly reset for two weeks"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('c99916e2-592f-5724-a803-622d42a47909','2570186a-c329-488a-b106-ddb003647ba7','Grow a Vegetable Garden','linear',true,false,'Home','From bare patch to actual harvest.','{"goals":[{"key":"g1","title":"Grow a Vegetable Garden","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pick the spot and what to grow"},{"key":"n2","parent":null,"title":"Prepare beds and soil"},{"key":"n3","parent":null,"title":"Plant your starts"},{"key":"n4","parent":null,"title":"Keep everything alive for a month"},{"key":"n5","parent":null,"title":"Harvest your first meal"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('509e8939-b924-57c4-bc77-708117c8334f','2570186a-c329-488a-b106-ddb003647ba7','Host a Dinner Party','linear',true,false,'Home','Six people, one table, food you cooked.','{"goals":[{"key":"g1","title":"Host a Dinner Party","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Set a date and invite six people"},{"key":"n2","parent":null,"title":"Plan a menu you can actually cook"},{"key":"n3","parent":null,"title":"Do a full trial run of the main"},{"key":"n4","parent":null,"title":"Host the night"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d2d7a7d1-eae9-58a7-a543-88e84342ffdf','2570186a-c329-488a-b106-ddb003647ba7','Cook Dinner at Home','habit',true,false,'Home','Weeknights come from your kitchen, not an app.','{"goals":[{"key":"g1","title":"Cook Dinner at Home","structure":"habit","days":[1,2,3,4,5],"cue":"I get home from work","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('e55e5e5a-3749-5cad-b3b4-73fc6fdd131c','2570186a-c329-488a-b106-ddb003647ba7','Adopt and Train a Dog','tree',true,false,'Home','Each skill unlocks more freedom for both of you.','{"goals":[{"key":"g1","title":"Adopt and Train a Dog","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Bring your dog home prepared"},{"key":"n2","parent":"n1","title":"House training solid"},{"key":"n3","parent":"n2","title":"Reliable recall at the park"},{"key":"n4","parent":"n3","title":"Off-leash trail hikes"},{"key":"n5","parent":"n1","title":"Sit, stay, leave it"},{"key":"n6","parent":"n5","title":"Loose-leash city walks"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('45e70935-dbe4-55c7-ae5f-52340cc0e821','2570186a-c329-488a-b106-ddb003647ba7','Weekly Date Night','habit',true,false,'Relationships','One protected evening a week, no logistics talk.','{"goals":[{"key":"g1","title":"Weekly Date Night","structure":"habit","days":[6],"cue":"Saturday dinner time arrives","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ff037e5b-8c80-5d64-b7df-9d8770a4d0be','2570186a-c329-488a-b106-ddb003647ba7','Plan a Trip Abroad','linear',true,false,'Adventure','From daydream to boarding pass.','{"goals":[{"key":"g1","title":"Plan a Trip Abroad","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Pick the country and dates"},{"key":"n2","parent":null,"title":"Set the budget and start saving"},{"key":"n3","parent":null,"title":"Book flights and beds"},{"key":"n4","parent":null,"title":"Plan the two must-do days"},{"key":"n5","parent":null,"title":"Go"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('95e94d40-4f9f-5782-b8ab-c42b66d448a3','2570186a-c329-488a-b106-ddb003647ba7','Make New Friends','tree',true,false,'Relationships','Small social reps that unlock a real circle.','{"goals":[{"key":"g1","title":"Make New Friends","structure":"tree","nodes":[{"key":"n1","parent":null,"title":"Join one recurring group or class"},{"key":"n2","parent":"n1","title":"Get one coffee with someone new"},{"key":"n3","parent":"n2","title":"Host a small hangout"},{"key":"n4","parent":"n3","title":"A standing monthly plan with friends"},{"key":"n5","parent":"n1","title":"Say yes to every invite for a month"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('5a7ed8a4-6d1e-5356-ba92-aa4dfa48f6a0','2570186a-c329-488a-b106-ddb003647ba7','Sub-30 5k','linear',true,false,'Fitness','You can run it — now run it faster.','{"goals":[{"key":"g1","title":"Sub-30 5k","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Baseline: time a current 5k"},{"key":"n2","parent":null,"title":"Weekly intervals for a month"},{"key":"n3","parent":null,"title":"Two tempo runs a week"},{"key":"n4","parent":null,"title":"Break 32 minutes"},{"key":"n5","parent":null,"title":"Break 30 minutes"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('582a3882-8f83-56de-b975-db1e00f96686','2570186a-c329-488a-b106-ddb003647ba7','Startup Validation Machine','machine',true,true,'Business','Prove people want it before you build it — interviews on a daily loop.','{"goals":[{"key":"g1","title":"Startup Validation Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Write the problem hypothesis","x":100,"y":80},{"key":"b","parent":null,"title":"Interview 15 potential customers","x":285,"y":80,"loop":15},{"key":"c","parent":null,"title":"Landing page smoke test","x":285,"y":195},{"key":"d","parent":null,"title":"Signal: 20 signups or 5 ''shut up and take my money''","x":470,"y":80},{"key":"e","parent":null,"title":"Build the tiny MVP","x":655,"y":80},{"key":"f","parent":null,"title":"First 3 paying users","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('41565694-ea83-56a6-813b-514c2aba54cc','2570186a-c329-488a-b106-ddb003647ba7','Launch a SaaS','machine',true,true,'Business','The build machine plus a daily shipping habit wired into it.','{"goals":[{"key":"g1","title":"Launch a SaaS","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick one painful problem","x":100,"y":80},{"key":"b","parent":null,"title":"Ship the MVP","x":285,"y":80,"hook":"g2.n3"},{"key":"c","parent":null,"title":"10 user interviews","x":285,"y":195,"loop":10},{"key":"d","parent":null,"title":"Set up payments","x":470,"y":80},{"key":"e","parent":null,"title":"First paying customer","x":470,"y":195},{"key":"f","parent":null,"title":"Reach $100 MRR","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","e"],["d","e"],["e","f"]]},{"key":"g2","title":"MVP build sprint","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Write the one-page spec"},{"key":"n2","parent":null,"title":"Build the core flow"},{"key":"n3","parent":null,"title":"Deploy it live"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('03356aca-6fef-54c9-a580-247bcd35c055','2570186a-c329-488a-b106-ddb003647ba7','First Freelance Client','machine',true,true,'Business','Three pitch channels running in parallel — any one of them lands it.','{"goals":[{"key":"g1","title":"First Freelance Client","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Define offer and rate","x":100,"y":195},{"key":"b","parent":null,"title":"Plan A: pitch your network","x":285,"y":80,"loop":10},{"key":"c","parent":null,"title":"Plan B: cold outreach","x":285,"y":195,"loop":20},{"key":"d","parent":null,"title":"Plan C: freelance platforms","x":285,"y":310,"loop":10},{"key":"e","parent":null,"title":"First discovery call","x":470,"y":195},{"key":"f","parent":null,"title":"Signed contract","x":655,"y":195}],"edges":[["a","b"],["a","c"],["a","d"],["b","e"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('98bdd76a-82a0-58fd-bc8e-da38c16d563d','2570186a-c329-488a-b106-ddb003647ba7','Ten Customers Machine','machine',true,true,'Business','A repeatable sales loop, not ten lucky breaks.','{"goals":[{"key":"g1","title":"Ten Customers Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Write the pitch that names the pain","x":100,"y":80},{"key":"b","parent":null,"title":"Daily outreach block","x":285,"y":80,"loop":20},{"key":"c","parent":null,"title":"Follow-up sequence live","x":285,"y":195},{"key":"d","parent":null,"title":"5 demos delivered","x":470,"y":80},{"key":"e","parent":null,"title":"Customers 1-3","x":470,"y":195},{"key":"f","parent":null,"title":"Customers 4-10","x":655,"y":195}],"edges":[["a","b"],["b","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('20e1c2cd-8b1e-5e28-b8ba-39ad8cdd08b3','2570186a-c329-488a-b106-ddb003647ba7','Raise Your Rates','machine',true,true,'Business','Proof, positioning, then the ask — with a fallback path.','{"goals":[{"key":"g1","title":"Raise Your Rates","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Document 3 client wins with numbers","x":100,"y":80},{"key":"b","parent":null,"title":"Research market rates","x":100,"y":195},{"key":"c","parent":null,"title":"New pricing page","x":285,"y":80},{"key":"d","parent":null,"title":"Plan A: raise for new clients","x":470,"y":80},{"key":"e","parent":null,"title":"Plan B: renegotiate one current client","x":470,"y":195},{"key":"f","parent":null,"title":"First project at the new rate","x":655,"y":80}],"edges":[["a","c"],["b","c"],["c","d"],["c","e"],["d","f"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('56dbd74f-7fcd-58bc-8b89-1bb167909942','2570186a-c329-488a-b106-ddb003647ba7','Content Engine','machine',true,true,'Business','A publishing machine driven by a five-day-a-week writing habit.','{"goals":[{"key":"g1","title":"Content Engine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick your lane and platform","x":100,"y":80},{"key":"b","parent":null,"title":"Publish 20 pieces","x":285,"y":80,"loop":20},{"key":"c","parent":null,"title":"Analyze the top 3 performers","x":470,"y":80},{"key":"d","parent":null,"title":"Double down: 10 more in the winning format","x":470,"y":195,"loop":10},{"key":"e","parent":null,"title":"1,000 followers","x":655,"y":195}],"edges":[["a","b"],["b","c"],["c","d"],["d","e"]]},{"key":"g2","title":"Daily writing block","structure":"habit","days":[1,2,3,4,5],"cue":"I pour my morning coffee","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('507a27b0-7f3c-587f-adc0-88c4c6cb4ae6','2570186a-c329-488a-b106-ddb003647ba7','Audience to 1k','machine',true,true,'Business','Two growth paths feeding one follower goal.','{"goals":[{"key":"g1","title":"Audience to 1k","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Nail your bio and niche","x":100,"y":195},{"key":"b","parent":null,"title":"Plan A: daily original posts","x":285,"y":80,"loop":30},{"key":"c","parent":null,"title":"Plan B: comment on 5 big accounts daily","x":285,"y":310,"loop":30},{"key":"d","parent":null,"title":"First post over 1k views","x":470,"y":195},{"key":"e","parent":null,"title":"500 followers","x":470,"y":310},{"key":"f","parent":null,"title":"1,000 followers","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('127ecf75-c60c-503c-814e-0642f53b7b08','2570186a-c329-488a-b106-ddb003647ba7','Etsy Shop Launch','machine',true,true,'Business','Product, shopfront, and the first-ten-sales grind.','{"goals":[{"key":"g1","title":"Etsy Shop Launch","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick one product to perfect","x":100,"y":80},{"key":"b","parent":null,"title":"Make 10 units","x":285,"y":80,"loop":10},{"key":"c","parent":null,"title":"Photograph like a catalog","x":285,"y":195},{"key":"d","parent":null,"title":"Shop live with 5 listings","x":470,"y":80},{"key":"e","parent":null,"title":"First sale","x":470,"y":195},{"key":"f","parent":null,"title":"Ten sales and 5 reviews","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('308d5aed-2219-54d0-b1e4-0b7c922d42c0','2570186a-c329-488a-b106-ddb003647ba7','Sell an Online Course','machine',true,true,'Business','Presell first — record only what people already bought.','{"goals":[{"key":"g1","title":"Sell an Online Course","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Outline the transformation","x":100,"y":80},{"key":"b","parent":null,"title":"Presell to 10 buyers","x":285,"y":80,"loop":10},{"key":"c","parent":null,"title":"Record module by module","x":470,"y":80,"loop":8},{"key":"d","parent":null,"title":"Deliver cohort one","x":655,"y":80},{"key":"e","parent":null,"title":"Collect testimonials and relaunch","x":655,"y":195}],"edges":[["a","b"],["b","c"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('7214c030-5488-5a87-8090-156a2b3bf30d','2570186a-c329-488a-b106-ddb003647ba7','Newsletter to 500','machine',true,true,'Business','A weekly issue habit hooked into the growth machine.','{"goals":[{"key":"g1","title":"Newsletter to 500 subscribers","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick the promise and name","x":100,"y":80},{"key":"b","parent":null,"title":"12 issues shipped","x":285,"y":80,"loop":12,"hook":"g2.n3"},{"key":"c","parent":null,"title":"Swap mentions with 3 newsletters","x":285,"y":195},{"key":"d","parent":null,"title":"100 subscribers","x":470,"y":80},{"key":"e","parent":null,"title":"500 subscribers","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Ship the first three issues","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Write issue #1"},{"key":"n2","parent":null,"title":"Issue #2 out"},{"key":"n3","parent":null,"title":"Issue #3 out \u2014 rhythm set"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('2c1f29f0-df04-5291-96ca-9fc1d5e84e38','2570186a-c329-488a-b106-ddb003647ba7','Job Search Machine','machine',true,true,'Career','Referrals, cold applications, and recruiters — three lanes into one offer.','{"goals":[{"key":"g1","title":"Job Search Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Resume and story sharpened","x":100,"y":195},{"key":"b","parent":null,"title":"Plan A: 15 warm referrals","x":285,"y":80,"loop":15},{"key":"c","parent":null,"title":"Plan B: 30 tailored applications","x":285,"y":195,"loop":30},{"key":"d","parent":null,"title":"Plan C: 5 recruiter relationships","x":285,"y":310},{"key":"e","parent":null,"title":"First onsite/final round","x":470,"y":195},{"key":"f","parent":null,"title":"Offer signed","x":655,"y":195}],"edges":[["a","b"],["a","c"],["a","d"],["b","e"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('a22de4fe-d928-5497-a4d3-c7267064e035','2570186a-c329-488a-b106-ddb003647ba7','Interview Prep System','machine',true,true,'Career','Daily problem reps feed the interview machine.','{"goals":[{"key":"g1","title":"Interview-ready","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Map the target role''s loop","x":100,"y":80},{"key":"b","parent":null,"title":"50 practice problems","x":285,"y":80,"loop":50,"hook":"g2.n3"},{"key":"c","parent":null,"title":"5 behavioral stories written","x":285,"y":195},{"key":"d","parent":null,"title":"3 full mock interviews","x":470,"y":80,"loop":3},{"key":"e","parent":null,"title":"Pass a real final round","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Problem-a-day ramp","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"10 easy problems"},{"key":"n2","parent":null,"title":"10 mediums"},{"key":"n3","parent":null,"title":"First hard solved"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('b081de2e-489e-5f92-9279-c503819fb5f2','2570186a-c329-488a-b106-ddb003647ba7','Negotiate a Raise','machine',true,true,'Career','Evidence, timing, and the meeting — with a plan B if it''s a no.','{"goals":[{"key":"g1","title":"Negotiate a Raise","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Write your impact doc","x":100,"y":80},{"key":"b","parent":null,"title":"Benchmark your market rate","x":100,"y":195},{"key":"c","parent":null,"title":"Schedule the conversation","x":285,"y":80},{"key":"d","parent":null,"title":"Make the ask","x":470,"y":80},{"key":"e","parent":null,"title":"Plan B: written growth plan with a date","x":655,"y":195},{"key":"f","parent":null,"title":"Raise secured","x":655,"y":80}],"edges":[["a","c"],["b","c"],["c","d"],["d","f"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('52335229-9208-5605-b00a-31b5c4005a18','2570186a-c329-488a-b106-ddb003647ba7','Career Change Without Going Broke','machine',true,true,'Career','Bridge income on one path while the new skill ramps on the other.','{"goals":[{"key":"g1","title":"Career Change Without Going Broke","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick the destination role","x":100,"y":195},{"key":"b","parent":null,"title":"6-month runway saved","x":285,"y":80},{"key":"c","parent":null,"title":"Core skill course done","x":285,"y":310,"loop":10},{"key":"d","parent":null,"title":"3 portfolio pieces in the new field","x":470,"y":310,"loop":3},{"key":"e","parent":null,"title":"First paid work in the new field","x":655,"y":195}],"edges":[["a","b"],["a","c"],["c","d"],["b","e"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('7e8b750e-6ebe-57d9-9e8d-5e27d06bdcc6','2570186a-c329-488a-b106-ddb003647ba7','Into Management','machine',true,true,'Career','Lead before the title, then make it official.','{"goals":[{"key":"g1","title":"Into Management","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Tell your manager the goal","x":100,"y":80},{"key":"b","parent":null,"title":"Lead one cross-team project","x":285,"y":80},{"key":"c","parent":null,"title":"Mentor two teammates","x":285,"y":195},{"key":"d","parent":null,"title":"Run the team''s planning once","x":470,"y":80},{"key":"e","parent":null,"title":"Formal title change","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d3e93861-4237-5b3c-93eb-45ce65b7b707','2570186a-c329-488a-b106-ddb003647ba7','Personal Brand Machine','machine',true,true,'Career','Speak, write, and connect — a system, with a weekly posting habit.','{"goals":[{"key":"g1","title":"Known in your field","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Define what you want to be known for","x":100,"y":80},{"key":"b","parent":null,"title":"20 public posts","x":285,"y":80,"loop":20},{"key":"c","parent":null,"title":"2 podcast/guest appearances","x":285,"y":195},{"key":"d","parent":null,"title":"Speak at one event","x":470,"y":195},{"key":"e","parent":null,"title":"Inbound opportunity arrives","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","e"],["c","d"],["d","e"]]},{"key":"g2","title":"Weekly visibility post","structure":"habit","days":[2],"cue":"Tuesday lunch ends","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('9da4f0d0-ec1a-5168-a7cd-7cd349b9fdde','2570186a-c329-488a-b106-ddb003647ba7','Speak at a Conference','machine',true,true,'Career','From abstract to applause, with meetups as the proving ground.','{"goals":[{"key":"g1","title":"Speak at a Conference","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick your talk topic","x":100,"y":80},{"key":"b","parent":null,"title":"Write the abstract","x":285,"y":80},{"key":"c","parent":null,"title":"Give it at 2 meetups first","x":285,"y":195,"loop":2},{"key":"d","parent":null,"title":"Submit to 5 CFPs","x":470,"y":80,"loop":5},{"key":"e","parent":null,"title":"Acceptance","x":470,"y":195},{"key":"f","parent":null,"title":"Deliver the talk","x":655,"y":195}],"edges":[["a","b"],["b","c"],["b","d"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('4dfcd28a-a6ff-5dc4-8eb2-426d35316eb8','2570186a-c329-488a-b106-ddb003647ba7','Find a Mentor','machine',true,true,'Career','Not an ask — an orbit. Add value until the relationship is real.','{"goals":[{"key":"g1","title":"Find a Mentor","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List 5 people a step ahead of you","x":100,"y":80},{"key":"b","parent":null,"title":"Engage with their work weekly","x":285,"y":80,"loop":8},{"key":"c","parent":null,"title":"Send one genuinely useful thing to each","x":285,"y":195},{"key":"d","parent":null,"title":"First real conversation","x":470,"y":80},{"key":"e","parent":null,"title":"Standing monthly chat","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('9f555ddb-2ebd-5cef-93ec-cf550ef54cf5','2570186a-c329-488a-b106-ddb003647ba7','Debt Payoff Machine','machine',true,true,'Money','Avalanche or snowball — pick a lane, keep the loop running.','{"goals":[{"key":"g1","title":"Debt Payoff Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List every debt with rates","x":100,"y":195},{"key":"b","parent":null,"title":"Plan A: avalanche (highest rate first)","x":285,"y":80},{"key":"c","parent":null,"title":"Plan B: snowball (smallest first)","x":285,"y":310},{"key":"d","parent":null,"title":"12 extra payments made","x":470,"y":195,"loop":12},{"key":"e","parent":null,"title":"First account at zero","x":470,"y":310},{"key":"f","parent":null,"title":"Halfway point crossed","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('6147224e-b6d6-51ac-af13-76db547e4062','2570186a-c329-488a-b106-ddb003647ba7','Down Payment System','machine',true,true,'Money','A savings machine with a no-spend habit hooked into its engine.','{"goals":[{"key":"g1","title":"House down payment","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Set the number and date","x":100,"y":80},{"key":"b","parent":null,"title":"Automate the monthly transfer","x":285,"y":80},{"key":"c","parent":null,"title":"12 months funded","x":470,"y":80,"loop":12,"hook":"g2.n3"},{"key":"d","parent":null,"title":"Side income adds 10%","x":470,"y":195},{"key":"e","parent":null,"title":"Down payment complete","x":655,"y":80}],"edges":[["a","b"],["b","c"],["b","d"],["c","e"],["d","e"]]},{"key":"g2","title":"Spending reset","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Full subscription audit"},{"key":"n2","parent":null,"title":"30-day no-impulse rule"},{"key":"n3","parent":null,"title":"Three lean months in a row"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('bcbeac60-255e-5d14-b1cd-ccc9bc38d6be','2570186a-c329-488a-b106-ddb003647ba7','Portfolio Setup Machine','machine',true,true,'Money','Accounts, allocation, automation — then leave it alone.','{"goals":[{"key":"g1","title":"Portfolio Setup Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Emergency fund confirmed","x":100,"y":80},{"key":"b","parent":null,"title":"Open retirement + brokerage accounts","x":285,"y":80},{"key":"c","parent":null,"title":"Write a one-page allocation plan","x":285,"y":195},{"key":"d","parent":null,"title":"Automate monthly contributions","x":470,"y":80},{"key":"e","parent":null,"title":"Six untouched months","x":655,"y":80,"loop":6}],"edges":[["a","b"],["b","d"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('4c6ecfdf-a947-59c3-a9f6-38eade65b2ee','2570186a-c329-488a-b106-ddb003647ba7','Side Income to $500/mo','machine',true,true,'Money','Two candidate streams race; the winner gets doubled down.','{"goals":[{"key":"g1","title":"Side Income to $500/mo","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick two income experiments","x":100,"y":195},{"key":"b","parent":null,"title":"Experiment A: 30 days","x":285,"y":80,"loop":30},{"key":"c","parent":null,"title":"Experiment B: 30 days","x":285,"y":310,"loop":30},{"key":"d","parent":null,"title":"First $100 month","x":470,"y":195},{"key":"e","parent":null,"title":"Kill the loser, double the winner","x":470,"y":310},{"key":"f","parent":null,"title":"$500 month","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('bcb25efc-20ff-5a9f-b0a8-71bb30f0f20e','2570186a-c329-488a-b106-ddb003647ba7','Cut the Bills 20%','machine',true,true,'Money','Every recurring cost interrogated, renegotiated, or executed.','{"goals":[{"key":"g1","title":"Cut the Bills 20%","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List every recurring charge","x":100,"y":80},{"key":"b","parent":null,"title":"Cancel the zombies","x":285,"y":80},{"key":"c","parent":null,"title":"Renegotiate 5 bills","x":285,"y":195,"loop":5},{"key":"d","parent":null,"title":"Switch 2 providers","x":470,"y":195},{"key":"e","parent":null,"title":"20% lower monthly burn","x":655,"y":80}],"edges":[["a","b"],["a","c"],["c","d"],["b","e"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('658de610-7804-5137-a4b2-97e546771885','2570186a-c329-488a-b106-ddb003647ba7','FIRE Starter System','machine',true,true,'Money','Savings-rate machine plus a monthly money-review habit.','{"goals":[{"key":"g1","title":"Path to financial independence","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Calculate your FI number","x":100,"y":80},{"key":"b","parent":null,"title":"Savings rate to 30%","x":285,"y":80},{"key":"c","parent":null,"title":"Savings rate to 50%","x":470,"y":80},{"key":"d","parent":null,"title":"One year at 50%","x":655,"y":80,"loop":12}],"edges":[["a","b"],["b","c"],["c","d"]]},{"key":"g2","title":"Monthly money review","structure":"habit","days":[0],"cue":"the first Sunday morning of the month","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('c23cbc66-ffc4-5359-92a9-8bef5d8b3d6d','2570186a-c329-488a-b106-ddb003647ba7','First Rental Property','machine',true,true,'Money','Education and capital in parallel; the deal only unlocks after both.','{"goals":[{"key":"g1","title":"First Rental Property","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Read 2 books, talk to 2 landlords","x":100,"y":80},{"key":"b","parent":null,"title":"Down payment fund complete","x":100,"y":310},{"key":"c","parent":null,"title":"Pick the target market","x":285,"y":80},{"key":"d","parent":null,"title":"Analyze 25 deals on paper","x":470,"y":80,"loop":25},{"key":"e","parent":null,"title":"Financing pre-approved","x":470,"y":310},{"key":"f","parent":null,"title":"Offer accepted and closed","x":655,"y":195}],"edges":[["a","c"],["c","d"],["b","e"],["d","f"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('3c5587b4-56ff-5482-978a-27b369b1a2da','2570186a-c329-488a-b106-ddb003647ba7','Marathon System','machine',true,true,'Fitness','The race machine, fueled by a four-day running habit hooked in.','{"goals":[{"key":"g1","title":"Run a marathon","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Get cleared and pick the race","x":100,"y":80},{"key":"b","parent":null,"title":"Base: 20 miles a week","x":285,"y":80,"loop":8,"hook":"g2.n3"},{"key":"c","parent":null,"title":"Long run to 15 miles","x":470,"y":80},{"key":"d","parent":null,"title":"Fuel + gear dialed in","x":470,"y":195},{"key":"e","parent":null,"title":"20-mile peak run","x":655,"y":80},{"key":"f","parent":null,"title":"Race day: 26.2","x":655,"y":195}],"edges":[["a","b"],["b","c"],["b","d"],["c","e"],["d","e"],["e","f"]]},{"key":"g2","title":"Base building block","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"Two weeks consistent"},{"key":"n2","parent":null,"title":"First 10-mile week"},{"key":"n3","parent":null,"title":"First 20-mile week"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('5e58feff-14ea-59fe-a320-17fb12986de0','2570186a-c329-488a-b106-ddb003647ba7','Strength Program','machine',true,true,'Fitness','A lifting machine with the gym habit welded on.','{"goals":[{"key":"g1","title":"Get strong","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Learn the big 4 lifts with a coach or video review","x":100,"y":80},{"key":"b","parent":null,"title":"12 weeks of progressive overload","x":285,"y":80,"loop":36},{"key":"c","parent":null,"title":"Bodyweight bench press","x":470,"y":80},{"key":"d","parent":null,"title":"1.5x bodyweight deadlift","x":655,"y":80}],"edges":[["a","b"],["b","c"],["c","d"]]},{"key":"g2","title":"Gym days","structure":"habit","days":[1,3,5],"cue":"I finish work","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('8bf84634-1d68-599d-b0a7-a911f6c8cec8','2570186a-c329-488a-b106-ddb003647ba7','Lose 20 lbs Machine','machine',true,true,'Fitness','Meal prep or tracking — either lane feeds the same result.','{"goals":[{"key":"g1","title":"Lose 20 lbs Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Baseline: weight, photos, measurements","x":100,"y":195},{"key":"b","parent":null,"title":"Plan A: Sunday meal prep","x":285,"y":80,"loop":12},{"key":"c","parent":null,"title":"Plan B: track every calorie","x":285,"y":310,"loop":30},{"key":"d","parent":null,"title":"First 5 lbs","x":470,"y":195},{"key":"e","parent":null,"title":"Halfway: 10 lbs","x":470,"y":310},{"key":"f","parent":null,"title":"20 lbs, held for a month","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ee295860-c4c1-58e4-aa98-756c291e3b28','2570186a-c329-488a-b106-ddb003647ba7','5k PR System','machine',true,true,'Fitness','Interval machine plus the weekly speedwork habit.','{"goals":[{"key":"g1","title":"5k personal record","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Time a baseline 5k","x":100,"y":80},{"key":"b","parent":null,"title":"8 interval sessions","x":285,"y":80,"loop":8},{"key":"c","parent":null,"title":"8 tempo runs","x":285,"y":195,"loop":8},{"key":"d","parent":null,"title":"Tune-up race or solo time trial","x":470,"y":80},{"key":"e","parent":null,"title":"PR day","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Track Tuesday","structure":"habit","days":[2],"cue":"Tuesday after work","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('51d3ba03-c754-5eeb-9069-c0eb72eac7f5','2570186a-c329-488a-b106-ddb003647ba7','Make the Team','machine',true,true,'Fitness','Skills, conditioning, and film — tryout as the boss level.','{"goals":[{"key":"g1","title":"Make the Team","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Get the tryout date and standards","x":100,"y":195},{"key":"b","parent":null,"title":"Daily skills block","x":285,"y":80,"loop":30},{"key":"c","parent":null,"title":"Conditioning to standard","x":285,"y":310,"loop":20},{"key":"d","parent":null,"title":"Scrimmage weekly","x":470,"y":195,"loop":6},{"key":"e","parent":null,"title":"Tryout day","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('b9986fc9-ffb7-53ab-af4d-898aa0089ec1','2570186a-c329-488a-b106-ddb003647ba7','Summit a Big Peak','machine',true,true,'Fitness','Fitness, gear, and route knowledge converge on summit day.','{"goals":[{"key":"g1","title":"Summit a Big Peak","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick the mountain and season","x":100,"y":195},{"key":"b","parent":null,"title":"Weekly training hikes","x":285,"y":80,"loop":12},{"key":"c","parent":null,"title":"Gear list bought and tested","x":285,"y":310},{"key":"d","parent":null,"title":"Two practice peaks","x":470,"y":80,"loop":2},{"key":"e","parent":null,"title":"Route and permits locked","x":470,"y":310},{"key":"f","parent":null,"title":"Summit day","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","e"],["d","f"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('9449ebe7-d8be-5002-85da-f1f3a03ee44b','2570186a-c329-488a-b106-ddb003647ba7','Triathlon Finisher','machine',true,true,'Fitness','Three sports, three tracks - swim, bike, run converge on race day.','{"goals":[{"key":"g1","title":"Triathlon Finisher","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Enter a sprint triathlon","x":100,"y":195},{"key":"b","parent":null,"title":"Swim track: 750m open water","x":285,"y":80,"loop":10},{"key":"c","parent":null,"title":"Bike track: 20k comfortable","x":285,"y":195,"loop":10},{"key":"d","parent":null,"title":"Run track: 5k off the bike","x":285,"y":310,"loop":8},{"key":"e","parent":null,"title":"Two full brick sessions","x":470,"y":195,"loop":2},{"key":"f","parent":null,"title":"Race day finish line","x":655,"y":195}],"edges":[["a","b"],["a","c"],["a","d"],["b","e"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('480e2455-f949-58f5-b271-2351ec29dbc0','2570186a-c329-488a-b106-ddb003647ba7','Language Fluency System','machine',true,true,'Learning','An immersion machine with daily flashcards hooked into its core.','{"goals":[{"key":"g1","title":"Speak a new language","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick your level test and date","x":100,"y":80},{"key":"b","parent":null,"title":"1,000 flashcards mastered","x":285,"y":80,"loop":50,"hook":"g2.n3"},{"key":"c","parent":null,"title":"20 tutoring sessions","x":285,"y":195,"loop":20},{"key":"d","parent":null,"title":"Media in target language only, 2 weeks","x":470,"y":80},{"key":"e","parent":null,"title":"30-minute conversation","x":470,"y":195},{"key":"f","parent":null,"title":"Pass the level test","x":655,"y":195}],"edges":[["a","b"],["a","c"],["b","d"],["c","e"],["d","e"],["e","f"]]},{"key":"g2","title":"Anki streak ramp","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"7-day streak"},{"key":"n2","parent":null,"title":"30-day streak"},{"key":"n3","parent":null,"title":"100-day streak"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('14266ee6-4dbf-51be-8d30-d9bf6c1ce342','2570186a-c329-488a-b106-ddb003647ba7','Job-Ready Developer','machine',true,true,'Learning','Course, projects, and interviews — one machine, one daily code habit.','{"goals":[{"key":"g1","title":"Hired as a developer","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Finish the core curriculum","x":100,"y":80,"loop":20},{"key":"b","parent":null,"title":"Build 3 portfolio projects","x":285,"y":80,"loop":3},{"key":"c","parent":null,"title":"Open source: 5 merged PRs","x":285,"y":195,"loop":5},{"key":"d","parent":null,"title":"Apply to 30 roles","x":470,"y":80,"loop":30},{"key":"e","parent":null,"title":"Offer","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Code every day","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"dinner is done","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('25e24c5c-f1c9-52b3-98f3-35a34429831e','2570186a-c329-488a-b106-ddb003647ba7','Grad School Application','machine',true,true,'Learning','Scores, essays, and references all converge on submission day.','{"goals":[{"key":"g1","title":"Grad School Application","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Shortlist 6 programs","x":100,"y":195},{"key":"b","parent":null,"title":"Test prep and sit the exam","x":285,"y":80,"loop":20},{"key":"c","parent":null,"title":"Statement drafted and reviewed 3x","x":285,"y":195,"loop":3},{"key":"d","parent":null,"title":"3 recommenders confirmed","x":285,"y":310},{"key":"e","parent":null,"title":"All applications submitted","x":470,"y":195},{"key":"f","parent":null,"title":"Acceptance in hand","x":655,"y":195}],"edges":[["a","b"],["a","c"],["a","d"],["b","e"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('d78f92e1-fca8-5271-a483-a6d484a41510','2570186a-c329-488a-b106-ddb003647ba7','Recital-Ready Musician','machine',true,true,'Learning','Performance machine plus the daily practice habit.','{"goals":[{"key":"g1","title":"Perform a full piece live","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Choose the piece","x":100,"y":80},{"key":"b","parent":null,"title":"Section-by-section mastery","x":285,"y":80,"loop":12},{"key":"c","parent":null,"title":"Full runthroughs from memory","x":470,"y":80,"loop":5},{"key":"d","parent":null,"title":"Play for 3 friendly audiences","x":470,"y":195,"loop":3},{"key":"e","parent":null,"title":"The real performance","x":655,"y":80}],"edges":[["a","b"],["b","c"],["c","d"],["c","e"],["d","e"]]},{"key":"g2","title":"Daily practice","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I get home","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('96af18ad-6410-5541-b361-95fa4481d6cf','2570186a-c329-488a-b106-ddb003647ba7','AI/ML Fundamentals','machine',true,true,'Learning','Math track and code track in parallel, merging at real projects.','{"goals":[{"key":"g1","title":"AI/ML Fundamentals","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Linear algebra + stats refresher","x":100,"y":80,"loop":10},{"key":"b","parent":null,"title":"Python + notebooks fluent","x":100,"y":310,"loop":10},{"key":"c","parent":null,"title":"Core ML course complete","x":285,"y":195,"loop":15},{"key":"d","parent":null,"title":"3 Kaggle-style projects","x":470,"y":195,"loop":3},{"key":"e","parent":null,"title":"Ship one real model","x":655,"y":195}],"edges":[["a","c"],["b","c"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('5726c229-b53f-5515-9aa6-e0ac6329505a','2570186a-c329-488a-b106-ddb003647ba7','Chess 1500 System','machine',true,true,'Learning','Tactics machine plus a daily puzzle habit.','{"goals":[{"key":"g1","title":"Reach 1500 rating","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Fix an opening repertoire","x":100,"y":80},{"key":"b","parent":null,"title":"1,000 puzzles","x":285,"y":80,"loop":50},{"key":"c","parent":null,"title":"Analyze 30 of your own games","x":285,"y":195,"loop":30},{"key":"d","parent":null,"title":"Endgame fundamentals course","x":470,"y":195},{"key":"e","parent":null,"title":"1500 achieved","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","e"],["c","d"],["d","e"]]},{"key":"g2","title":"Daily puzzles","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"my lunch break starts","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('cacd3161-4d76-547f-b972-e550ea961fc3','2570186a-c329-488a-b106-ddb003647ba7','Publish Technical Articles','machine',true,true,'Learning','Write, syndicate, repeat — until editors come to you.','{"goals":[{"key":"g1","title":"Publish Technical Articles","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List 10 article ideas from your work","x":100,"y":80},{"key":"b","parent":null,"title":"Publish 6 articles","x":285,"y":80,"loop":6},{"key":"c","parent":null,"title":"Syndicate to 2 bigger outlets","x":470,"y":80},{"key":"d","parent":null,"title":"One article hits 10k reads","x":470,"y":195},{"key":"e","parent":null,"title":"Invited to write or speak","x":655,"y":80}],"edges":[["a","b"],["b","c"],["b","d"],["c","e"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('e49d1018-d3ea-5cee-a6a2-f1c129ffa874','2570186a-c329-488a-b106-ddb003647ba7','Novel Writing System','machine',true,true,'Creative','The book machine, powered by a 500-words-a-day habit hooked in.','{"goals":[{"key":"g1","title":"Finish a novel","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Premise and outline locked","x":100,"y":80},{"key":"b","parent":null,"title":"First draft: 60k words","x":285,"y":80,"loop":60,"hook":"g2.n3"},{"key":"c","parent":null,"title":"Rest it for 4 weeks","x":470,"y":80},{"key":"d","parent":null,"title":"Revision pass two","x":470,"y":195},{"key":"e","parent":null,"title":"3 beta readers report back","x":655,"y":80,"loop":3},{"key":"f","parent":null,"title":"Query or publish","x":655,"y":195}],"edges":[["a","b"],["b","c"],["c","d"],["d","e"],["e","f"]]},{"key":"g2","title":"Drafting milestones","structure":"linear","nodes":[{"key":"n1","parent":null,"title":"First 10k words"},{"key":"n2","parent":null,"title":"Halfway: 30k"},{"key":"n3","parent":null,"title":"THE END typed"}]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('4ace9216-d3cc-5337-b28e-87b26621eefc','2570186a-c329-488a-b106-ddb003647ba7','Podcast Launch System','machine',true,true,'Creative','Launch machine plus a weekly recording habit.','{"goals":[{"key":"g1","title":"Launch a podcast","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Format, name, and cover art","x":100,"y":80},{"key":"b","parent":null,"title":"Bank 5 episodes before launch","x":285,"y":80,"loop":5},{"key":"c","parent":null,"title":"Publish launch trio at once","x":470,"y":80},{"key":"d","parent":null,"title":"10 episodes live","x":470,"y":195,"loop":7},{"key":"e","parent":null,"title":"1,000 total downloads","x":655,"y":195}],"edges":[["a","b"],["b","c"],["c","d"],["d","e"]]},{"key":"g2","title":"Recording day","structure":"habit","days":[4],"cue":"Thursday evening starts","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('090ee99a-c6d3-5ca3-9e0f-cf0836228ff5','2570186a-c329-488a-b106-ddb003647ba7','Short Film Machine','machine',true,true,'Creative','Script, crew, shoot, cut — festival as the final boss.','{"goals":[{"key":"g1","title":"Short Film Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Write the 10-page script","x":100,"y":80,"loop":3},{"key":"b","parent":null,"title":"Cast and crew locked","x":285,"y":80},{"key":"c","parent":null,"title":"Locations and gear","x":285,"y":195},{"key":"d","parent":null,"title":"Shoot weekend","x":470,"y":80},{"key":"e","parent":null,"title":"Edit and sound mix","x":470,"y":195,"loop":6},{"key":"f","parent":null,"title":"Submit to 5 festivals","x":655,"y":195,"loop":5}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('066a4932-7745-591b-a37e-239cd6d35cc9','2570186a-c329-488a-b106-ddb003647ba7','Commission Business','machine',true,true,'Creative','Turn your art into orders — portfolio machine plus practice habit.','{"goals":[{"key":"g1","title":"Open for commissions","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Define styles and price sheet","x":100,"y":80},{"key":"b","parent":null,"title":"10 portfolio pieces","x":285,"y":80,"loop":10},{"key":"c","parent":null,"title":"Commission page live","x":470,"y":80},{"key":"d","parent":null,"title":"First 3 paid commissions","x":470,"y":195,"loop":3},{"key":"e","parent":null,"title":"Booked a month out","x":655,"y":195}],"edges":[["a","b"],["b","c"],["c","d"],["d","e"]]},{"key":"g2","title":"Daily art hour","structure":"habit","days":[0,1,2,3,4,5,6],"cue":"I finish dinner","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('fb54446a-073a-595b-851e-1c0b3557b92d','2570186a-c329-488a-b106-ddb003647ba7','Kindle Publishing Machine','machine',true,true,'Creative','Write to market, launch clean, then do it again smarter.','{"goals":[{"key":"g1","title":"Kindle Publishing Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick the niche and comp titles","x":100,"y":80},{"key":"b","parent":null,"title":"Draft complete","x":285,"y":80,"loop":30},{"key":"c","parent":null,"title":"Pro cover + edit","x":285,"y":195},{"key":"d","parent":null,"title":"Launch with 10 early reviews","x":470,"y":80,"loop":10},{"key":"e","parent":null,"title":"First 100 sales","x":655,"y":80}],"edges":[["a","b"],["b","c"],["b","d"],["c","d"],["d","e"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('cecf709d-1583-587b-b2c3-7869e019b028','2570186a-c329-488a-b106-ddb003647ba7','Streaming Channel Growth','machine',true,true,'Creative','Consistency machine plus a fixed streaming schedule habit.','{"goals":[{"key":"g1","title":"Grow a streaming channel","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Niche, overlay, and setup done","x":100,"y":80},{"key":"b","parent":null,"title":"30 streams completed","x":285,"y":80,"loop":30},{"key":"c","parent":null,"title":"Clips pipeline to shorts","x":285,"y":195,"loop":15},{"key":"d","parent":null,"title":"First 50 followers","x":470,"y":80},{"key":"e","parent":null,"title":"Affiliate/partner threshold","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Stream nights","structure":"habit","days":[2,4,6],"cue":"8pm hits","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('7643c63a-467b-590b-b228-2e04afe7d9b7','2570186a-c329-488a-b106-ddb003647ba7','Wedding Planning Machine','machine',true,true,'Life','Venue, people, and money on parallel tracks — one perfect day out the end.','{"goals":[{"key":"g1","title":"Wedding Planning Machine","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Budget and guest count agreed","x":100,"y":195},{"key":"b","parent":null,"title":"Venue and date locked","x":285,"y":80},{"key":"c","parent":null,"title":"Vendors: food, photo, music","x":285,"y":195,"loop":3},{"key":"d","parent":null,"title":"Invites out, RSVPs tracked","x":470,"y":80},{"key":"e","parent":null,"title":"Attire and rings done","x":470,"y":310},{"key":"f","parent":null,"title":"Final walkthrough week","x":655,"y":195},{"key":"g","parent":null,"title":"The day","x":655,"y":310}],"edges":[["a","b"],["a","c"],["b","d"],["c","f"],["d","f"],["e","f"],["f","g"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('1c8d0040-9643-5925-b861-5572dc27103b','2570186a-c329-488a-b106-ddb003647ba7','Move to a New City','machine',true,true,'Life','Job, home, and logistics — arrive with a life, not just boxes.','{"goals":[{"key":"g1","title":"Move to a New City","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Pick the city and target date","x":100,"y":195},{"key":"b","parent":null,"title":"Income secured there","x":285,"y":80},{"key":"c","parent":null,"title":"Housing locked","x":285,"y":195},{"key":"d","parent":null,"title":"Purge and pack","x":285,"y":310,"loop":10},{"key":"e","parent":null,"title":"The move itself","x":470,"y":195},{"key":"f","parent":null,"title":"First month: 3 new people, 3 favorite spots","x":655,"y":195}],"edges":[["a","b"],["a","c"],["a","d"],["b","e"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('a66239c9-cf90-5cb6-9ba9-af47eb14333c','2570186a-c329-488a-b106-ddb003647ba7','Renovate a Room','machine',true,true,'Life','Design, budget, demo, build — a real project plan for the house.','{"goals":[{"key":"g1","title":"Renovate a Room","structure":"machine","nodes":[{"key":"a","parent":null,"title":"Design and mood board","x":100,"y":80},{"key":"b","parent":null,"title":"Budget and materials list","x":100,"y":195},{"key":"c","parent":null,"title":"Demo weekend","x":285,"y":80},{"key":"d","parent":null,"title":"Trades or DIY blocks booked","x":285,"y":195},{"key":"e","parent":null,"title":"Build and install","x":470,"y":80,"loop":8},{"key":"f","parent":null,"title":"Finishing touches and reveal","x":655,"y":80}],"edges":[["a","c"],["b","c"],["b","d"],["c","e"],["d","e"],["e","f"]]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('060c9047-e122-5315-b006-395f0859861f','2570186a-c329-488a-b106-ddb003647ba7','Life Admin Machine','machine',true,true,'Life','Clear the backlog once, then a weekly review keeps it at zero.','{"goals":[{"key":"g1","title":"Life admin at zero","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List every open loop in one place","x":100,"y":80},{"key":"b","parent":null,"title":"Knock out 20 backlog items","x":285,"y":80,"loop":20},{"key":"c","parent":null,"title":"Automate bills and renewals","x":285,"y":195},{"key":"d","parent":null,"title":"Paperwork filed, digital organized","x":470,"y":80},{"key":"e","parent":null,"title":"Inbox and admin at zero","x":655,"y":80}],"edges":[["a","b"],["a","c"],["b","d"],["c","d"],["d","e"]]},{"key":"g2","title":"Weekly review","structure":"habit","days":[0],"cue":"Sunday coffee","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
insert into public.goal_templates (id, author_id, title, structure, official, pro, category, description, body) values
('ecbed8db-32cf-5b8a-ae3d-a758a7959a3c','2570186a-c329-488a-b106-ddb003647ba7','Year of Adventure','machine',true,true,'Life','Twelve trips in twelve months — machine plus a monthly planning habit.','{"goals":[{"key":"g1","title":"12 adventures in 12 months","structure":"machine","nodes":[{"key":"a","parent":null,"title":"List 20 candidate adventures","x":100,"y":80},{"key":"b","parent":null,"title":"Adventure fund automated","x":100,"y":195},{"key":"c","parent":null,"title":"Complete adventures 1-6","x":285,"y":80,"loop":6},{"key":"d","parent":null,"title":"One trip that scares you a little","x":470,"y":80},{"key":"e","parent":null,"title":"Complete adventures 7-12","x":655,"y":80,"loop":6}],"edges":[["a","c"],["b","c"],["c","d"],["d","e"]]},{"key":"g2","title":"First-Saturday planning","structure":"habit","days":[6],"cue":"the first Saturday morning of the month","nodes":[]}]}'::jsonb)
on conflict (id) do nothing;
