/**
 * How a goal is organized:
 * - linear: a straight path, one milestone after another
 * - pyramid: nested sub-goals under one root goal
 * - tree: like a game skill tree — completing a node unlocks its children
 * - habit: repeats on a weekly schedule with streaks; no milestones
 * - machine: Pro — a free-form process graph with paths, loops, and hooks
 */
export type GoalStructure = "linear" | "pyramid" | "tree" | "habit" | "machine";

export interface Goal {
  id: string;
  /** free-form goal title (the database column keeps its legacy name "identity") */
  identity: string;
  /** legacy field, no longer collected but still displayed if present */
  why: string;
  structure: GoalStructure;
  /** habit goals: scheduled weekdays (0 = Sunday … 6 = Saturday); null otherwise */
  days: number[] | null;
  /** habit goals: stacking cue, shown as "After {cue}, I will {title}" */
  cue: string;
  /** optional target date as a YYYY-MM-DD key */
  deadline: string | null;
  createdAt: string;
}

export interface Milestone {
  id: string;
  goalId: string;
  /** parent milestone for pyramid/tree structures; null for roots and linear */
  parentId: string | null;
  title: string;
  /** order among siblings, 1-based */
  position: number;
  /** machine goals: free-form canvas position */
  x: number | null;
  y: number | null;
  /** loop nodes complete after this many reps (max one per day); null = plain step */
  loopTarget: number | null;
  loopCount: number;
  /** date key of the last counted rep, enforcing one per day */
  loopLast: string | null;
  /** Pro hooks: auto-completes when this other milestone completes */
  hookSourceId: string | null;
  completedAt: string | null;
  createdAt: string;
}

/** machine goals: a directed path between two steps */
export interface MachineEdge {
  id: string;
  goalId: string;
  fromId: string;
  toId: string;
}

export interface AppState {
  goals: Goal[];
  milestones: Milestone[];
  edges: MachineEdge[];
  /** habit goalId -> completed dates as YYYY-MM-DD keys */
  habitCompletions: Record<string, string[]>;
  pro: boolean;
}

export const FREE_GOAL_LIMIT = 2;

/** one node inside a template part; `hook` references "partKey.nodeKey" */
export interface TemplateNode {
  key: string;
  parent: string | null;
  title: string;
  x?: number | null;
  y?: number | null;
  loop?: number | null;
  hook?: string | null;
}

/** one goal generated by a template */
export interface TemplatePart {
  key: string;
  title: string;
  structure: GoalStructure;
  days?: number[] | null;
  cue?: string;
  nodes: TemplateNode[];
  edges?: [string, string][];
}

/** a template body: one or more goals, possibly hooked together */
export interface TemplateBundle {
  goals: TemplatePart[];
}
